# - name: Pull and Run docker image
#   hosts: all
#   tasks:
#     - name: Pull woolllff/databaseApp
#       docker_image:
#         name: woolllff/databaseApp
#         source: pull
#       # vars:
#       #   - ansible_python_interpreter: /usr/bin/python


---
- hosts: all
  become: true

  tasks:
    - name: remove docker images
      shell: docker image rm -f woolllff/databaseapp:latest
    - name: Pull woolllff/databaseapp
      shell: docker pull woolllff/databaseapp:latest
    - name: stop  docker container
      shell: docker stop dbapp
    - name: remove docker container
      shell : docker rm dbapp 
    - name: run the docker container
      shell: docker run -d -p 3000:3000 --name dbapp woolllff/databaseapp:latest